services:
  - type: web
    name: calculadora-luz-api
    env: python
    plan: free
    region: oregon
    runtime: python-3.11.9
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHONPATH
        value: /opt/render/project/src